// Major world languages - expanded for China trade partners
export const MAJOR_LANGUAGES = [
  // 全球主要语言
  { id: 'en', name: '英语', nameEn: 'English', color: '#3B82F6' },
  { id: 'zh', name: '中文', nameEn: 'Chinese', color: '#EF4444' },
  { id: 'es', name: '西班牙语', nameEn: 'Spanish', color: '#F59E0B' },
  { id: 'ar', name: '阿拉伯语', nameEn: 'Arabic', color: '#10B981' },
  { id: 'fr', name: '法语', nameEn: 'French', color: '#8B5CF6' },
  { id: 'ru', name: '俄语', nameEn: 'Russian', color: '#EC4899' },
  { id: 'pt', name: '葡萄牙语', nameEn: 'Portuguese', color: '#14B8A6' },
  { id: 'de', name: '德语', nameEn: 'German', color: '#F97316' },
  { id: 'ja', name: '日语', nameEn: 'Japanese', color: '#6366F1' },
  { id: 'hi', name: '印地语', nameEn: 'Hindi', color: '#84CC16' },
  // 东亚/东南亚 - 中国重要贸易伙伴
  { id: 'ko', name: '韩语', nameEn: 'Korean', color: '#0EA5E9' },
  { id: 'vi', name: '越南语', nameEn: 'Vietnamese', color: '#22C55E' },
  { id: 'th', name: '泰语', nameEn: 'Thai', color: '#A855F7' },
  { id: 'id', name: '印尼语', nameEn: 'Indonesian', color: '#DC2626' },
  { id: 'ms', name: '马来语', nameEn: 'Malay', color: '#0891B2' },
  { id: 'tl', name: '菲律宾语', nameEn: 'Filipino', color: '#4ADE80' },
  // 中东/中亚
  { id: 'fa', name: '波斯语', nameEn: 'Persian', color: '#B45309' },
  { id: 'tr', name: '土耳其语', nameEn: 'Turkish', color: '#E11D48' },
  // 欧洲
  { id: 'nl', name: '荷兰语', nameEn: 'Dutch', color: '#FB923C' },
  { id: 'it', name: '意大利语', nameEn: 'Italian', color: '#059669' },
  { id: 'pl', name: '波兰语', nameEn: 'Polish', color: '#DC2626' },
];

export interface CountryLanguageInfo {
  iso3: string;           // ISO 3166-1 alpha-3 code
  name: string;           // Country name in Chinese
  nameEn: string;         // Country name in English
  flag: string;           // Emoji flag
  primaryLanguage: string;     // Primary/official language
  secondaryLanguages: string[]; // Other major languages
  englishProficiency: 'high' | 'medium' | 'low' | 'native'; // English proficiency level
  languages: string[];    // All major languages spoken (language IDs)
  // New fields for business communication
  googleMapsLang?: string;      // Google Maps default language in this country
  businessLang?: string;        // Recommended language for business emails/WhatsApp
  businessLangAlt?: string;     // Alternative business language
  businessNote?: string;        // Notes about business communication
  preferredMessenger?: 'whatsapp' | 'wechat' | 'line' | 'kakaotalk' | 'telegram' | 'viber' | 'other'; // Preferred messaging app
  whatsappPopularity?: 'high' | 'medium' | 'low'; // WhatsApp usage level
}

// Messenger info for display
export const MESSENGER_INFO: Record<string, { name: string; icon: string; color: string }> = {
  whatsapp: { name: 'WhatsApp', icon: '💬', color: '#25D366' },
  wechat: { name: '微信 WeChat', icon: '💚', color: '#07C160' },
  line: { name: 'LINE', icon: '💚', color: '#00B900' },
  kakaotalk: { name: 'KakaoTalk', icon: '💛', color: '#FEE500' },
  telegram: { name: 'Telegram', icon: '✈️', color: '#0088CC' },
  viber: { name: 'Viber', icon: '💜', color: '#7360F2' },
  other: { name: '其他', icon: '📱', color: '#6B7280' },
};

// Country language data - ISO 3166-1 alpha-3 codes
export const COUNTRY_LANGUAGES: Record<string, CountryLanguageInfo> = {
  // North America
  USA: {
    iso3: 'USA',
    name: '美国',
    nameEn: 'United States',
    flag: '🇺🇸',
    primaryLanguage: '英语',
    secondaryLanguages: ['西班牙语'],
    englishProficiency: 'native',
    languages: ['en', 'es'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessNote: '直接用英语，部分地区可用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  CAN: {
    iso3: 'CAN',
    name: '加拿大',
    nameEn: 'Canada',
    flag: '🇨🇦',
    primaryLanguage: '英语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'native',
    languages: ['en', 'fr'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessLangAlt: '法语',
    businessNote: '魁北克地区建议用法语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  MEX: {
    iso3: 'MEX',
    name: '墨西哥',
    nameEn: 'Mexico',
    flag: '🇲🇽',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessLangAlt: '英语',
    businessNote: '强烈建议用西班牙语，英语接受度低',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },

  // South America
  BRA: {
    iso3: 'BRA',
    name: '巴西',
    nameEn: 'Brazil',
    flag: '🇧🇷',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
    googleMapsLang: '葡萄牙语',
    businessLang: '葡萄牙语',
    businessNote: '必须用葡萄牙语，英语普及率很低',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ARG: {
    iso3: 'ARG',
    name: '阿根廷',
    nameEn: 'Argentina',
    flag: '🇦🇷',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语，英语接受度低',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  CHL: {
    iso3: 'CHL',
    name: '智利',
    nameEn: 'Chile',
    flag: '🇨🇱',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  COL: {
    iso3: 'COL',
    name: '哥伦比亚',
    nameEn: 'Colombia',
    flag: '🇨🇴',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  PER: {
    iso3: 'PER',
    name: '秘鲁',
    nameEn: 'Peru',
    flag: '🇵🇪',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  VEN: {
    iso3: 'VEN',
    name: '委内瑞拉',
    nameEn: 'Venezuela',
    flag: '🇻🇪',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ECU: {
    iso3: 'ECU',
    name: '厄瓜多尔',
    nameEn: 'Ecuador',
    flag: '🇪🇨',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  BOL: {
    iso3: 'BOL',
    name: '玻利维亚',
    nameEn: 'Bolivia',
    flag: '🇧🇴',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  PRY: {
    iso3: 'PRY',
    name: '巴拉圭',
    nameEn: 'Paraguay',
    flag: '🇵🇾',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  URY: {
    iso3: 'URY',
    name: '乌拉圭',
    nameEn: 'Uruguay',
    flag: '🇺🇾',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },

  // Europe
  GBR: {
    iso3: 'GBR',
    name: '英国',
    nameEn: 'United Kingdom',
    flag: '🇬🇧',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessNote: '直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  DEU: {
    iso3: 'DEU',
    name: '德国',
    nameEn: 'Germany',
    flag: '🇩🇪',
    primaryLanguage: '德语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['de', 'en'],
    googleMapsLang: '德语',
    businessLang: '英语',
    businessLangAlt: '德语',
    businessNote: '英语可行，德语更显专业',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  FRA: {
    iso3: 'FRA',
    name: '法国',
    nameEn: 'France',
    flag: '🇫🇷',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['fr'],
    googleMapsLang: '法语',
    businessLang: '法语',
    businessLangAlt: '英语',
    businessNote: '建议用法语，法国人偏好本国语言',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ITA: {
    iso3: 'ITA',
    name: '意大利',
    nameEn: 'Italy',
    flag: '🇮🇹',
    primaryLanguage: '意大利语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['it'],
    googleMapsLang: '意大利语',
    businessLang: '意大利语',
    businessLangAlt: '英语',
    businessNote: '建议用意大利语，北部英语稍好',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ESP: {
    iso3: 'ESP',
    name: '西班牙',
    nameEn: 'Spain',
    flag: '🇪🇸',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['es'],
    googleMapsLang: '西班牙语',
    businessLang: '西班牙语',
    businessLangAlt: '英语',
    businessNote: '建议用西班牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  PRT: {
    iso3: 'PRT',
    name: '葡萄牙',
    nameEn: 'Portugal',
    flag: '🇵🇹',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['pt'],
    googleMapsLang: '葡萄牙语',
    businessLang: '葡萄牙语',
    businessLangAlt: '英语',
    businessNote: '建议用葡萄牙语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  NLD: {
    iso3: 'NLD',
    name: '荷兰',
    nameEn: 'Netherlands',
    flag: '🇳🇱',
    primaryLanguage: '荷兰语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['nl', 'en'],
    googleMapsLang: '荷兰语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语即可',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  BEL: {
    iso3: 'BEL',
    name: '比利时',
    nameEn: 'Belgium',
    flag: '🇧🇪',
    primaryLanguage: '荷兰语',
    secondaryLanguages: ['法语', '德语'],
    englishProficiency: 'high',
    languages: ['fr', 'de'],
    googleMapsLang: '荷兰语/法语',
    businessLang: '英语',
    businessLangAlt: '法语',
    businessNote: '英语可行，南部用法语、北部用荷兰语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  CHE: {
    iso3: 'CHE',
    name: '瑞士',
    nameEn: 'Switzerland',
    flag: '🇨🇭',
    primaryLanguage: '德语',
    secondaryLanguages: ['法语', '意大利语'],
    englishProficiency: 'high',
    languages: ['de', 'fr'],
    googleMapsLang: '德语/法语',
    businessLang: '英语',
    businessLangAlt: '德语',
    businessNote: '英语可行，看地区选择德/法/意语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  AUT: {
    iso3: 'AUT',
    name: '奥地利',
    nameEn: 'Austria',
    flag: '🇦🇹',
    primaryLanguage: '德语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['de'],
    googleMapsLang: '德语',
    businessLang: '英语',
    businessLangAlt: '德语',
    businessNote: '英语可行，德语更佳',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  POL: {
    iso3: 'POL',
    name: '波兰',
    nameEn: 'Poland',
    flag: '🇵🇱',
    primaryLanguage: '波兰语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['pl'],
    googleMapsLang: '波兰语',
    businessLang: '英语',
    businessLangAlt: '波兰语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  SWE: {
    iso3: 'SWE',
    name: '瑞典',
    nameEn: 'Sweden',
    flag: '🇸🇪',
    primaryLanguage: '瑞典语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
    googleMapsLang: '瑞典语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  NOR: {
    iso3: 'NOR',
    name: '挪威',
    nameEn: 'Norway',
    flag: '🇳🇴',
    primaryLanguage: '挪威语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
    googleMapsLang: '挪威语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  DNK: {
    iso3: 'DNK',
    name: '丹麦',
    nameEn: 'Denmark',
    flag: '🇩🇰',
    primaryLanguage: '丹麦语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
    googleMapsLang: '丹麦语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  FIN: {
    iso3: 'FIN',
    name: '芬兰',
    nameEn: 'Finland',
    flag: '🇫🇮',
    primaryLanguage: '芬兰语',
    secondaryLanguages: ['瑞典语'],
    englishProficiency: 'high',
    languages: ['en'],
    googleMapsLang: '芬兰语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  IRL: {
    iso3: 'IRL',
    name: '爱尔兰',
    nameEn: 'Ireland',
    flag: '🇮🇪',
    primaryLanguage: '英语',
    secondaryLanguages: ['爱尔兰语'],
    englishProficiency: 'native',
    languages: ['en'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessNote: '直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  RUS: {
    iso3: 'RUS',
    name: '俄罗斯',
    nameEn: 'Russia',
    flag: '🇷🇺',
    primaryLanguage: '俄语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ru'],
    googleMapsLang: '俄语',
    businessLang: '俄语',
    businessLangAlt: '英语',
    businessNote: '强烈建议用俄语，英语普及率低',
    preferredMessenger: 'telegram',
    whatsappPopularity: 'medium',
  },
  UKR: {
    iso3: 'UKR',
    name: '乌克兰',
    nameEn: 'Ukraine',
    flag: '🇺🇦',
    primaryLanguage: '乌克兰语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
    googleMapsLang: '乌克兰语',
    businessLang: '乌克兰语',
    businessLangAlt: '英语',
    businessNote: '建议用乌克兰语或俄语',
    preferredMessenger: 'telegram',
    whatsappPopularity: 'medium',
  },
  GRC: {
    iso3: 'GRC',
    name: '希腊',
    nameEn: 'Greece',
    flag: '🇬🇷',
    primaryLanguage: '希腊语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
    googleMapsLang: '希腊语',
    businessLang: '英语',
    businessLangAlt: '希腊语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  CZE: {
    iso3: 'CZE',
    name: '捷克',
    nameEn: 'Czech Republic',
    flag: '🇨🇿',
    primaryLanguage: '捷克语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
    googleMapsLang: '捷克语',
    businessLang: '英语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  HUN: {
    iso3: 'HUN',
    name: '匈牙利',
    nameEn: 'Hungary',
    flag: '🇭🇺',
    primaryLanguage: '匈牙利语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
    googleMapsLang: '匈牙利语',
    businessLang: '英语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ROU: {
    iso3: 'ROU',
    name: '罗马尼亚',
    nameEn: 'Romania',
    flag: '🇷🇴',
    primaryLanguage: '罗马尼亚语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
    googleMapsLang: '罗马尼亚语',
    businessLang: '英语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },

  // Asia
  CHN: {
    iso3: 'CHN',
    name: '中国',
    nameEn: 'China',
    flag: '🇨🇳',
    primaryLanguage: '中文',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['zh'],
    googleMapsLang: '中文',
    businessLang: '中文',
    businessNote: '必须用中文，WhatsApp被封需用微信',
    preferredMessenger: 'wechat',
    whatsappPopularity: 'low',
  },
  JPN: {
    iso3: 'JPN',
    name: '日本',
    nameEn: 'Japan',
    flag: '🇯🇵',
    primaryLanguage: '日语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ja'],
    googleMapsLang: '日语',
    businessLang: '日语',
    businessLangAlt: '英语',
    businessNote: '强烈建议用日语，英语接受度低，常用LINE',
    preferredMessenger: 'line',
    whatsappPopularity: 'low',
  },
  KOR: {
    iso3: 'KOR',
    name: '韩国',
    nameEn: 'South Korea',
    flag: '🇰🇷',
    primaryLanguage: '韩语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['ko'],
    googleMapsLang: '韩语',
    businessLang: '韩语',
    businessLangAlt: '英语',
    businessNote: '建议用韩语，常用KakaoTalk',
    preferredMessenger: 'kakaotalk',
    whatsappPopularity: 'low',
  },
  IND: {
    iso3: 'IND',
    name: '印度',
    nameEn: 'India',
    flag: '🇮🇳',
    primaryLanguage: '印地语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['hi', 'en'],
    googleMapsLang: '英语/印地语',
    businessLang: '英语',
    businessNote: '英语可行，是商务通用语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  PAK: {
    iso3: 'PAK',
    name: '巴基斯坦',
    nameEn: 'Pakistan',
    flag: '🇵🇰',
    primaryLanguage: '乌尔都语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
    googleMapsLang: '乌尔都语',
    businessLang: '英语',
    businessNote: '英语可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  BGD: {
    iso3: 'BGD',
    name: '孟加拉国',
    nameEn: 'Bangladesh',
    flag: '🇧🇩',
    primaryLanguage: '孟加拉语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
    googleMapsLang: '孟加拉语',
    businessLang: '英语',
    businessLangAlt: '孟加拉语',
    businessNote: '英语在商务场合可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  IDN: {
    iso3: 'IDN',
    name: '印度尼西亚',
    nameEn: 'Indonesia',
    flag: '🇮🇩',
    primaryLanguage: '印尼语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['id'],
    googleMapsLang: '印尼语',
    businessLang: '印尼语',
    businessLangAlt: '英语',
    businessNote: '建议用印尼语，大企业英语可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  MYS: {
    iso3: 'MYS',
    name: '马来西亚',
    nameEn: 'Malaysia',
    flag: '🇲🇾',
    primaryLanguage: '马来语',
    secondaryLanguages: ['英语', '中文'],
    englishProficiency: 'high',
    languages: ['ms', 'en', 'zh'],
    googleMapsLang: '马来语',
    businessLang: '英语',
    businessLangAlt: '中文',
    businessNote: '英语流利，华人客户可用中文',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  SGP: {
    iso3: 'SGP',
    name: '新加坡',
    nameEn: 'Singapore',
    flag: '🇸🇬',
    primaryLanguage: '英语',
    secondaryLanguages: ['中文', '马来语'],
    englishProficiency: 'native',
    languages: ['en', 'zh'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessLangAlt: '中文',
    businessNote: '英语为主，华人客户可用中文',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  THA: {
    iso3: 'THA',
    name: '泰国',
    nameEn: 'Thailand',
    flag: '🇹🇭',
    primaryLanguage: '泰语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['th'],
    googleMapsLang: '泰语',
    businessLang: '泰语',
    businessLangAlt: '英语',
    businessNote: '建议用泰语，大企业英语可行',
    preferredMessenger: 'line',
    whatsappPopularity: 'medium',
  },
  VNM: {
    iso3: 'VNM',
    name: '越南',
    nameEn: 'Vietnam',
    flag: '🇻🇳',
    primaryLanguage: '越南语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['vi'],
    googleMapsLang: '越南语',
    businessLang: '越南语',
    businessLangAlt: '英语',
    businessNote: '建议用越南语，年轻一代英语稍好',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  PHL: {
    iso3: 'PHL',
    name: '菲律宾',
    nameEn: 'Philippines',
    flag: '🇵🇭',
    primaryLanguage: '菲律宾语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['tl', 'en'],
    googleMapsLang: '英语',
    businessLang: '英语',
    businessNote: '英语流利，直接用英语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  MMR: {
    iso3: 'MMR',
    name: '缅甸',
    nameEn: 'Myanmar',
    flag: '🇲🇲',
    primaryLanguage: '缅甸语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
    googleMapsLang: '缅甸语',
    businessLang: '缅甸语',
    businessLangAlt: '英语',
    businessNote: '建议用缅甸语',
    preferredMessenger: 'viber',
    whatsappPopularity: 'medium',
  },
  KHM: {
    iso3: 'KHM',
    name: '柬埔寨',
    nameEn: 'Cambodia',
    flag: '🇰🇭',
    primaryLanguage: '高棉语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
    googleMapsLang: '高棉语',
    businessLang: '高棉语',
    businessLangAlt: '英语',
    businessNote: '建议用高棉语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  TWN: {
    iso3: 'TWN',
    name: '台湾',
    nameEn: 'Taiwan',
    flag: '🇹🇼',
    primaryLanguage: '中文',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['zh'],
    googleMapsLang: '中文',
    businessLang: '中文',
    businessNote: '用繁体中文',
    preferredMessenger: 'line',
    whatsappPopularity: 'low',
  },
  HKG: {
    iso3: 'HKG',
    name: '香港',
    nameEn: 'Hong Kong',
    flag: '🇭🇰',
    primaryLanguage: '中文',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['zh', 'en'],
    googleMapsLang: '中文',
    businessLang: '英语',
    businessLangAlt: '中文',
    businessNote: '英语或繁体中文均可',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },

  // Middle East
  SAU: {
    iso3: 'SAU',
    name: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    flag: '🇸🇦',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['ar'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessLangAlt: '英语',
    businessNote: '阿拉伯语为主，大企业英语可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ARE: {
    iso3: 'ARE',
    name: '阿联酋',
    nameEn: 'UAE',
    flag: '🇦🇪',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['ar', 'en'],
    googleMapsLang: '阿拉伯语',
    businessLang: '英语',
    businessLangAlt: '阿拉伯语',
    businessNote: '英语广泛使用，阿拉伯语显尊重',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  QAT: {
    iso3: 'QAT',
    name: '卡塔尔',
    nameEn: 'Qatar',
    flag: '🇶🇦',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['ar', 'en'],
    googleMapsLang: '阿拉伯语',
    businessLang: '英语',
    businessLangAlt: '阿拉伯语',
    businessNote: '英语广泛使用',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  KWT: {
    iso3: 'KWT',
    name: '科威特',
    nameEn: 'Kuwait',
    flag: '🇰🇼',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['ar'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessLangAlt: '英语',
    businessNote: '阿拉伯语为主，英语可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  IRQ: {
    iso3: 'IRQ',
    name: '伊拉克',
    nameEn: 'Iraq',
    flag: '🇮🇶',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessNote: '建议用阿拉伯语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  IRN: {
    iso3: 'IRN',
    name: '伊朗',
    nameEn: 'Iran',
    flag: '🇮🇷',
    primaryLanguage: '波斯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fa'],
    googleMapsLang: '波斯语',
    businessLang: '波斯语',
    businessLangAlt: '英语',
    businessNote: '建议用波斯语，WhatsApp受限',
    preferredMessenger: 'telegram',
    whatsappPopularity: 'low',
  },
  TUR: {
    iso3: 'TUR',
    name: '土耳其',
    nameEn: 'Turkey',
    flag: '🇹🇷',
    primaryLanguage: '土耳其语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['tr'],
    googleMapsLang: '土耳其语',
    businessLang: '土耳其语',
    businessLangAlt: '英语',
    businessNote: '强烈建议用土耳其语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  ISR: {
    iso3: 'ISR',
    name: '以色列',
    nameEn: 'Israel',
    flag: '🇮🇱',
    primaryLanguage: '希伯来语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'high',
    languages: ['ar', 'en'],
    googleMapsLang: '希伯来语',
    businessLang: '英语',
    businessLangAlt: '希伯来语',
    businessNote: '英语流利',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  JOR: {
    iso3: 'JOR',
    name: '约旦',
    nameEn: 'Jordan',
    flag: '🇯🇴',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['ar'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessLangAlt: '英语',
    businessNote: '阿拉伯语为主，英语可行',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  LBN: {
    iso3: 'LBN',
    name: '黎巴嫩',
    nameEn: 'Lebanon',
    flag: '🇱🇧',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'medium',
    languages: ['ar', 'fr'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessLangAlt: '法语',
    businessNote: '阿拉伯语为主，法语也常用',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'high',
  },
  SYR: {
    iso3: 'SYR',
    name: '叙利亚',
    nameEn: 'Syria',
    flag: '🇸🇾',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
    googleMapsLang: '阿拉伯语',
    businessLang: '阿拉伯语',
    businessNote: '用阿拉伯语',
    preferredMessenger: 'whatsapp',
    whatsappPopularity: 'medium',
  },
  KAZ: {
    iso3: 'KAZ',
    name: '哈萨克斯坦',
    nameEn: 'Kazakhstan',
    flag: '🇰🇿',
    primaryLanguage: '哈萨克语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  UZB: {
    iso3: 'UZB',
    name: '乌兹别克斯坦',
    nameEn: 'Uzbekistan',
    flag: '🇺🇿',
    primaryLanguage: '乌兹别克语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  TKM: {
    iso3: 'TKM',
    name: '土库曼斯坦',
    nameEn: 'Turkmenistan',
    flag: '🇹🇲',
    primaryLanguage: '土库曼语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  TJK: {
    iso3: 'TJK',
    name: '塔吉克斯坦',
    nameEn: 'Tajikistan',
    flag: '🇹🇯',
    primaryLanguage: '塔吉克语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  KGZ: {
    iso3: 'KGZ',
    name: '吉尔吉斯斯坦',
    nameEn: 'Kyrgyzstan',
    flag: '🇰🇬',
    primaryLanguage: '吉尔吉斯语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },

  // Africa
  EGY: {
    iso3: 'EGY',
    name: '埃及',
    nameEn: 'Egypt',
    flag: '🇪🇬',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  ZAF: {
    iso3: 'ZAF',
    name: '南非',
    nameEn: 'South Africa',
    flag: '🇿🇦',
    primaryLanguage: '英语',
    secondaryLanguages: ['祖鲁语', '科萨语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  NGA: {
    iso3: 'NGA',
    name: '尼日利亚',
    nameEn: 'Nigeria',
    flag: '🇳🇬',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  KEN: {
    iso3: 'KEN',
    name: '肯尼亚',
    nameEn: 'Kenya',
    flag: '🇰🇪',
    primaryLanguage: '斯瓦希里语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  ETH: {
    iso3: 'ETH',
    name: '埃塞俄比亚',
    nameEn: 'Ethiopia',
    flag: '🇪🇹',
    primaryLanguage: '阿姆哈拉语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
  },
  GHA: {
    iso3: 'GHA',
    name: '加纳',
    nameEn: 'Ghana',
    flag: '🇬🇭',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  MAR: {
    iso3: 'MAR',
    name: '摩洛哥',
    nameEn: 'Morocco',
    flag: '🇲🇦',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['ar', 'fr'],
  },
  DZA: {
    iso3: 'DZA',
    name: '阿尔及利亚',
    nameEn: 'Algeria',
    flag: '🇩🇿',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['ar', 'fr'],
  },
  TUN: {
    iso3: 'TUN',
    name: '突尼斯',
    nameEn: 'Tunisia',
    flag: '🇹🇳',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['ar', 'fr'],
  },
  UGA: {
    iso3: 'UGA',
    name: '乌干达',
    nameEn: 'Uganda',
    flag: '🇺🇬',
    primaryLanguage: '英语',
    secondaryLanguages: ['斯瓦希里语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  TZA: {
    iso3: 'TZA',
    name: '坦桑尼亚',
    nameEn: 'Tanzania',
    flag: '🇹🇿',
    primaryLanguage: '斯瓦希里语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  AGO: {
    iso3: 'AGO',
    name: '安哥拉',
    nameEn: 'Angola',
    flag: '🇦🇴',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
  },
  MOZ: {
    iso3: 'MOZ',
    name: '莫桑比克',
    nameEn: 'Mozambique',
    flag: '🇲🇿',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
  },
  CMR: {
    iso3: 'CMR',
    name: '喀麦隆',
    nameEn: 'Cameroon',
    flag: '🇨🇲',
    primaryLanguage: '法语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['fr', 'en'],
  },
  CIV: {
    iso3: 'CIV',
    name: '科特迪瓦',
    nameEn: "Cote d'Ivoire",
    flag: '🇨🇮',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  SEN: {
    iso3: 'SEN',
    name: '塞内加尔',
    nameEn: 'Senegal',
    flag: '🇸🇳',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },

  // Oceania
  AUS: {
    iso3: 'AUS',
    name: '澳大利亚',
    nameEn: 'Australia',
    flag: '🇦🇺',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  NZL: {
    iso3: 'NZL',
    name: '新西兰',
    nameEn: 'New Zealand',
    flag: '🇳🇿',
    primaryLanguage: '英语',
    secondaryLanguages: ['毛利语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  PNG: {
    iso3: 'PNG',
    name: '巴布亚新几内亚',
    nameEn: 'Papua New Guinea',
    flag: '🇵🇬',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  FJI: {
    iso3: 'FJI',
    name: '斐济',
    nameEn: 'Fiji',
    flag: '🇫🇯',
    primaryLanguage: '英语',
    secondaryLanguages: ['斐济语'],
    englishProficiency: 'high',
    languages: ['en'],
  },

  // Additional European Countries
  BLR: {
    iso3: 'BLR',
    name: '白俄罗斯',
    nameEn: 'Belarus',
    flag: '🇧🇾',
    primaryLanguage: '白俄罗斯语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  SRB: {
    iso3: 'SRB',
    name: '塞尔维亚',
    nameEn: 'Serbia',
    flag: '🇷🇸',
    primaryLanguage: '塞尔维亚语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  HRV: {
    iso3: 'HRV',
    name: '克罗地亚',
    nameEn: 'Croatia',
    flag: '🇭🇷',
    primaryLanguage: '克罗地亚语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  BGR: {
    iso3: 'BGR',
    name: '保加利亚',
    nameEn: 'Bulgaria',
    flag: '🇧🇬',
    primaryLanguage: '保加利亚语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  SVK: {
    iso3: 'SVK',
    name: '斯洛伐克',
    nameEn: 'Slovakia',
    flag: '🇸🇰',
    primaryLanguage: '斯洛伐克语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  SVN: {
    iso3: 'SVN',
    name: '斯洛文尼亚',
    nameEn: 'Slovenia',
    flag: '🇸🇮',
    primaryLanguage: '斯洛文尼亚语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  LTU: {
    iso3: 'LTU',
    name: '立陶宛',
    nameEn: 'Lithuania',
    flag: '🇱🇹',
    primaryLanguage: '立陶宛语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'medium',
    languages: ['ru'],
  },
  LVA: {
    iso3: 'LVA',
    name: '拉脱维亚',
    nameEn: 'Latvia',
    flag: '🇱🇻',
    primaryLanguage: '拉脱维亚语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'medium',
    languages: ['ru'],
  },
  EST: {
    iso3: 'EST',
    name: '爱沙尼亚',
    nameEn: 'Estonia',
    flag: '🇪🇪',
    primaryLanguage: '爱沙尼亚语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'high',
    languages: ['en', 'ru'],
  },
  ALB: {
    iso3: 'ALB',
    name: '阿尔巴尼亚',
    nameEn: 'Albania',
    flag: '🇦🇱',
    primaryLanguage: '阿尔巴尼亚语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
  },
  MKD: {
    iso3: 'MKD',
    name: '北马其顿',
    nameEn: 'North Macedonia',
    flag: '🇲🇰',
    primaryLanguage: '马其顿语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  BIH: {
    iso3: 'BIH',
    name: '波黑',
    nameEn: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    primaryLanguage: '波斯尼亚语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  MNE: {
    iso3: 'MNE',
    name: '黑山',
    nameEn: 'Montenegro',
    flag: '🇲🇪',
    primaryLanguage: '黑山语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  MDA: {
    iso3: 'MDA',
    name: '摩尔多瓦',
    nameEn: 'Moldova',
    flag: '🇲🇩',
    primaryLanguage: '摩尔多瓦语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  LUX: {
    iso3: 'LUX',
    name: '卢森堡',
    nameEn: 'Luxembourg',
    flag: '🇱🇺',
    primaryLanguage: '法语',
    secondaryLanguages: ['德语'],
    englishProficiency: 'high',
    languages: ['fr', 'de', 'en'],
  },
  ISL: {
    iso3: 'ISL',
    name: '冰岛',
    nameEn: 'Iceland',
    flag: '🇮🇸',
    primaryLanguage: '冰岛语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  CYP: {
    iso3: 'CYP',
    name: '塞浦路斯',
    nameEn: 'Cyprus',
    flag: '🇨🇾',
    primaryLanguage: '希腊语',
    secondaryLanguages: ['土耳其语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  MLT: {
    iso3: 'MLT',
    name: '马耳他',
    nameEn: 'Malta',
    flag: '🇲🇹',
    primaryLanguage: '马耳他语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'native',
    languages: ['en'],
  },

  // Additional Asian Countries
  MNG: {
    iso3: 'MNG',
    name: '蒙古',
    nameEn: 'Mongolia',
    flag: '🇲🇳',
    primaryLanguage: '蒙古语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: [],
  },
  NPL: {
    iso3: 'NPL',
    name: '尼泊尔',
    nameEn: 'Nepal',
    flag: '🇳🇵',
    primaryLanguage: '尼泊尔语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
  },
  LKA: {
    iso3: 'LKA',
    name: '斯里兰卡',
    nameEn: 'Sri Lanka',
    flag: '🇱🇰',
    primaryLanguage: '僧伽罗语',
    secondaryLanguages: ['泰米尔语', '英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  LAO: {
    iso3: 'LAO',
    name: '老挝',
    nameEn: 'Laos',
    flag: '🇱🇦',
    primaryLanguage: '老挝语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
  },
  PRK: {
    iso3: 'PRK',
    name: '朝鲜',
    nameEn: 'North Korea',
    flag: '🇰🇵',
    primaryLanguage: '朝鲜语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: [],
  },
  AFG: {
    iso3: 'AFG',
    name: '阿富汗',
    nameEn: 'Afghanistan',
    flag: '🇦🇫',
    primaryLanguage: '达里语',
    secondaryLanguages: ['普什图语'],
    englishProficiency: 'low',
    languages: [],
  },
  YEM: {
    iso3: 'YEM',
    name: '也门',
    nameEn: 'Yemen',
    flag: '🇾🇪',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  BHR: {
    iso3: 'BHR',
    name: '巴林',
    nameEn: 'Bahrain',
    flag: '🇧🇭',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['ar', 'en'],
  },
  OMN: {
    iso3: 'OMN',
    name: '阿曼',
    nameEn: 'Oman',
    flag: '🇴🇲',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['ar'],
  },
  GEO: {
    iso3: 'GEO',
    name: '格鲁吉亚',
    nameEn: 'Georgia',
    flag: '🇬🇪',
    primaryLanguage: '格鲁吉亚语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  ARM: {
    iso3: 'ARM',
    name: '亚美尼亚',
    nameEn: 'Armenia',
    flag: '🇦🇲',
    primaryLanguage: '亚美尼亚语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  AZE: {
    iso3: 'AZE',
    name: '阿塞拜疆',
    nameEn: 'Azerbaijan',
    flag: '🇦🇿',
    primaryLanguage: '阿塞拜疆语',
    secondaryLanguages: ['俄语'],
    englishProficiency: 'low',
    languages: ['ru'],
  },
  BTN: {
    iso3: 'BTN',
    name: '不丹',
    nameEn: 'Bhutan',
    flag: '🇧🇹',
    primaryLanguage: '宗卡语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  BRN: {
    iso3: 'BRN',
    name: '文莱',
    nameEn: 'Brunei',
    flag: '🇧🇳',
    primaryLanguage: '马来语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  TLS: {
    iso3: 'TLS',
    name: '东帝汶',
    nameEn: 'Timor-Leste',
    flag: '🇹🇱',
    primaryLanguage: '德顿语',
    secondaryLanguages: ['葡萄牙语'],
    englishProficiency: 'low',
    languages: ['pt'],
  },
  MDV: {
    iso3: 'MDV',
    name: '马尔代夫',
    nameEn: 'Maldives',
    flag: '🇲🇻',
    primaryLanguage: '迪维希语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },

  // Additional African Countries
  LBY: {
    iso3: 'LBY',
    name: '利比亚',
    nameEn: 'Libya',
    flag: '🇱🇾',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  SDN: {
    iso3: 'SDN',
    name: '苏丹',
    nameEn: 'Sudan',
    flag: '🇸🇩',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  SSD: {
    iso3: 'SSD',
    name: '南苏丹',
    nameEn: 'South Sudan',
    flag: '🇸🇸',
    primaryLanguage: '英语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'medium',
    languages: ['en', 'ar'],
  },
  COD: {
    iso3: 'COD',
    name: '刚果(金)',
    nameEn: 'DR Congo',
    flag: '🇨🇩',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  COG: {
    iso3: 'COG',
    name: '刚果(布)',
    nameEn: 'Republic of Congo',
    flag: '🇨🇬',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  MDG: {
    iso3: 'MDG',
    name: '马达加斯加',
    nameEn: 'Madagascar',
    flag: '🇲🇬',
    primaryLanguage: '马达加斯加语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  ZWE: {
    iso3: 'ZWE',
    name: '津巴布韦',
    nameEn: 'Zimbabwe',
    flag: '🇿🇼',
    primaryLanguage: '英语',
    secondaryLanguages: ['绍纳语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  ZMB: {
    iso3: 'ZMB',
    name: '赞比亚',
    nameEn: 'Zambia',
    flag: '🇿🇲',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  BWA: {
    iso3: 'BWA',
    name: '博茨瓦纳',
    nameEn: 'Botswana',
    flag: '🇧🇼',
    primaryLanguage: '英语',
    secondaryLanguages: ['茨瓦纳语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  NAM: {
    iso3: 'NAM',
    name: '纳米比亚',
    nameEn: 'Namibia',
    flag: '🇳🇦',
    primaryLanguage: '英语',
    secondaryLanguages: ['南非荷兰语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  NER: {
    iso3: 'NER',
    name: '尼日尔',
    nameEn: 'Niger',
    flag: '🇳🇪',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  MLI: {
    iso3: 'MLI',
    name: '马里',
    nameEn: 'Mali',
    flag: '🇲🇱',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  BFA: {
    iso3: 'BFA',
    name: '布基纳法索',
    nameEn: 'Burkina Faso',
    flag: '🇧🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  TCD: {
    iso3: 'TCD',
    name: '乍得',
    nameEn: 'Chad',
    flag: '🇹🇩',
    primaryLanguage: '法语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'low',
    languages: ['fr', 'ar'],
  },
  RWA: {
    iso3: 'RWA',
    name: '卢旺达',
    nameEn: 'Rwanda',
    flag: '🇷🇼',
    primaryLanguage: '卢旺达语',
    secondaryLanguages: ['法语', '英语'],
    englishProficiency: 'medium',
    languages: ['fr', 'en'],
  },
  MRT: {
    iso3: 'MRT',
    name: '毛里塔尼亚',
    nameEn: 'Mauritania',
    flag: '🇲🇷',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['ar', 'fr'],
  },
  ERI: {
    iso3: 'ERI',
    name: '厄立特里亚',
    nameEn: 'Eritrea',
    flag: '🇪🇷',
    primaryLanguage: '提格雷尼亚语',
    secondaryLanguages: ['阿拉伯语', '英语'],
    englishProficiency: 'low',
    languages: ['ar', 'en'],
  },
  SOM: {
    iso3: 'SOM',
    name: '索马里',
    nameEn: 'Somalia',
    flag: '🇸🇴',
    primaryLanguage: '索马里语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  BEN: {
    iso3: 'BEN',
    name: '贝宁',
    nameEn: 'Benin',
    flag: '🇧🇯',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  TGO: {
    iso3: 'TGO',
    name: '多哥',
    nameEn: 'Togo',
    flag: '🇹🇬',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  GAB: {
    iso3: 'GAB',
    name: '加蓬',
    nameEn: 'Gabon',
    flag: '🇬🇦',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  SLE: {
    iso3: 'SLE',
    name: '塞拉利昂',
    nameEn: 'Sierra Leone',
    flag: '🇸🇱',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  LBR: {
    iso3: 'LBR',
    name: '利比里亚',
    nameEn: 'Liberia',
    flag: '🇱🇷',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  GIN: {
    iso3: 'GIN',
    name: '几内亚',
    nameEn: 'Guinea',
    flag: '🇬🇳',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  GMB: {
    iso3: 'GMB',
    name: '冈比亚',
    nameEn: 'Gambia',
    flag: '🇬🇲',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  CAF: {
    iso3: 'CAF',
    name: '中非',
    nameEn: 'Central African Republic',
    flag: '🇨🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  GNQ: {
    iso3: 'GNQ',
    name: '赤道几内亚',
    nameEn: 'Equatorial Guinea',
    flag: '🇬🇶',
    primaryLanguage: '西班牙语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['es', 'fr'],
  },
  BDI: {
    iso3: 'BDI',
    name: '布隆迪',
    nameEn: 'Burundi',
    flag: '🇧🇮',
    primaryLanguage: '基隆迪语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  MWI: {
    iso3: 'MWI',
    name: '马拉维',
    nameEn: 'Malawi',
    flag: '🇲🇼',
    primaryLanguage: '英语',
    secondaryLanguages: ['齐切瓦语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  LSO: {
    iso3: 'LSO',
    name: '莱索托',
    nameEn: 'Lesotho',
    flag: '🇱🇸',
    primaryLanguage: '塞索托语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  SWZ: {
    iso3: 'SWZ',
    name: '斯威士兰',
    nameEn: 'Eswatini',
    flag: '🇸🇿',
    primaryLanguage: '斯威士语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  DJI: {
    iso3: 'DJI',
    name: '吉布提',
    nameEn: 'Djibouti',
    flag: '🇩🇯',
    primaryLanguage: '法语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'low',
    languages: ['fr', 'ar'],
  },
  GNB: {
    iso3: 'GNB',
    name: '几内亚比绍',
    nameEn: 'Guinea-Bissau',
    flag: '🇬🇼',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
  },
  CPV: {
    iso3: 'CPV',
    name: '佛得角',
    nameEn: 'Cape Verde',
    flag: '🇨🇻',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
  },
  MUS: {
    iso3: 'MUS',
    name: '毛里求斯',
    nameEn: 'Mauritius',
    flag: '🇲🇺',
    primaryLanguage: '英语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'high',
    languages: ['en', 'fr'],
  },
  SYC: {
    iso3: 'SYC',
    name: '塞舌尔',
    nameEn: 'Seychelles',
    flag: '🇸🇨',
    primaryLanguage: '塞舌尔克里奥尔语',
    secondaryLanguages: ['英语', '法语'],
    englishProficiency: 'high',
    languages: ['en', 'fr'],
  },
  COM: {
    iso3: 'COM',
    name: '科摩罗',
    nameEn: 'Comoros',
    flag: '🇰🇲',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['法语'],
    englishProficiency: 'low',
    languages: ['ar', 'fr'],
  },
  STP: {
    iso3: 'STP',
    name: '圣多美和普林西比',
    nameEn: 'São Tomé and Príncipe',
    flag: '🇸🇹',
    primaryLanguage: '葡萄牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['pt'],
  },

  // Additional Americas Countries
  GTM: {
    iso3: 'GTM',
    name: '危地马拉',
    nameEn: 'Guatemala',
    flag: '🇬🇹',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  HND: {
    iso3: 'HND',
    name: '洪都拉斯',
    nameEn: 'Honduras',
    flag: '🇭🇳',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  SLV: {
    iso3: 'SLV',
    name: '萨尔瓦多',
    nameEn: 'El Salvador',
    flag: '🇸🇻',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  NIC: {
    iso3: 'NIC',
    name: '尼加拉瓜',
    nameEn: 'Nicaragua',
    flag: '🇳🇮',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  CRI: {
    iso3: 'CRI',
    name: '哥斯达黎加',
    nameEn: 'Costa Rica',
    flag: '🇨🇷',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['es'],
  },
  PAN: {
    iso3: 'PAN',
    name: '巴拿马',
    nameEn: 'Panama',
    flag: '🇵🇦',
    primaryLanguage: '西班牙语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['es', 'en'],
  },
  CUB: {
    iso3: 'CUB',
    name: '古巴',
    nameEn: 'Cuba',
    flag: '🇨🇺',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  JAM: {
    iso3: 'JAM',
    name: '牙买加',
    nameEn: 'Jamaica',
    flag: '🇯🇲',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  HTI: {
    iso3: 'HTI',
    name: '海地',
    nameEn: 'Haiti',
    flag: '🇭🇹',
    primaryLanguage: '法语',
    secondaryLanguages: ['海地克里奥尔语'],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  DOM: {
    iso3: 'DOM',
    name: '多米尼加',
    nameEn: 'Dominican Republic',
    flag: '🇩🇴',
    primaryLanguage: '西班牙语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['es'],
  },
  PRI: {
    iso3: 'PRI',
    name: '波多黎各',
    nameEn: 'Puerto Rico',
    flag: '🇵🇷',
    primaryLanguage: '西班牙语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['es', 'en'],
  },
  SUR: {
    iso3: 'SUR',
    name: '苏里南',
    nameEn: 'Suriname',
    flag: '🇸🇷',
    primaryLanguage: '荷兰语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: [],
  },
  GUY: {
    iso3: 'GUY',
    name: '圭亚那',
    nameEn: 'Guyana',
    flag: '🇬🇾',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  BLZ: {
    iso3: 'BLZ',
    name: '伯利兹',
    nameEn: 'Belize',
    flag: '🇧🇿',
    primaryLanguage: '英语',
    secondaryLanguages: ['西班牙语'],
    englishProficiency: 'native',
    languages: ['en', 'es'],
  },
  TTO: {
    iso3: 'TTO',
    name: '特立尼达和多巴哥',
    nameEn: 'Trinidad and Tobago',
    flag: '🇹🇹',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  BHS: {
    iso3: 'BHS',
    name: '巴哈马',
    nameEn: 'Bahamas',
    flag: '🇧🇸',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  BRB: {
    iso3: 'BRB',
    name: '巴巴多斯',
    nameEn: 'Barbados',
    flag: '🇧🇧',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },

  // Pacific Island Countries
  WSM: {
    iso3: 'WSM',
    name: '萨摩亚',
    nameEn: 'Samoa',
    flag: '🇼🇸',
    primaryLanguage: '萨摩亚语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  TON: {
    iso3: 'TON',
    name: '汤加',
    nameEn: 'Tonga',
    flag: '🇹🇴',
    primaryLanguage: '汤加语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  VUT: {
    iso3: 'VUT',
    name: '瓦努阿图',
    nameEn: 'Vanuatu',
    flag: '🇻🇺',
    primaryLanguage: '比斯拉马语',
    secondaryLanguages: ['英语', '法语'],
    englishProficiency: 'medium',
    languages: ['en', 'fr'],
  },
  SLB: {
    iso3: 'SLB',
    name: '所罗门群岛',
    nameEn: 'Solomon Islands',
    flag: '🇸🇧',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  NCL: {
    iso3: 'NCL',
    name: '新喀里多尼亚',
    nameEn: 'New Caledonia',
    flag: '🇳🇨',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  PYF: {
    iso3: 'PYF',
    name: '法属波利尼西亚',
    nameEn: 'French Polynesia',
    flag: '🇵🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },

  // Additional special regions
  PSE: {
    iso3: 'PSE',
    name: '巴勒斯坦',
    nameEn: 'Palestine',
    flag: '🇵🇸',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['ar'],
  },
  XKX: {
    iso3: 'XKX',
    name: '科索沃',
    nameEn: 'Kosovo',
    flag: '🇽🇰',
    primaryLanguage: '阿尔巴尼亚语',
    secondaryLanguages: ['塞尔维亚语'],
    englishProficiency: 'medium',
    languages: [],
  },
  ESH: {
    iso3: 'ESH',
    name: '西撒哈拉',
    nameEn: 'Western Sahara',
    flag: '🇪🇭',
    primaryLanguage: '阿拉伯语',
    secondaryLanguages: ['西班牙语'],
    englishProficiency: 'low',
    languages: ['ar', 'es'],
  },

  // Overseas territories and special regions
  GRL: {
    iso3: 'GRL',
    name: '格陵兰',
    nameEn: 'Greenland',
    flag: '🇬🇱',
    primaryLanguage: '格陵兰语',
    secondaryLanguages: ['丹麦语'],
    englishProficiency: 'medium',
    languages: [],
  },
  GUF: {
    iso3: 'GUF',
    name: '法属圭亚那',
    nameEn: 'French Guiana',
    flag: '🇬🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  REU: {
    iso3: 'REU',
    name: '留尼汪',
    nameEn: 'Réunion',
    flag: '🇷🇪',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  GLP: {
    iso3: 'GLP',
    name: '瓜德罗普',
    nameEn: 'Guadeloupe',
    flag: '🇬🇵',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  MTQ: {
    iso3: 'MTQ',
    name: '马提尼克',
    nameEn: 'Martinique',
    flag: '🇲🇶',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  MYT: {
    iso3: 'MYT',
    name: '马约特',
    nameEn: 'Mayotte',
    flag: '🇾🇹',
    primaryLanguage: '法语',
    secondaryLanguages: ['阿拉伯语'],
    englishProficiency: 'low',
    languages: ['fr', 'ar'],
  },
  FRO: {
    iso3: 'FRO',
    name: '法罗群岛',
    nameEn: 'Faroe Islands',
    flag: '🇫🇴',
    primaryLanguage: '法罗语',
    secondaryLanguages: ['丹麦语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  ALA: {
    iso3: 'ALA',
    name: '奥兰群岛',
    nameEn: 'Åland Islands',
    flag: '🇦🇽',
    primaryLanguage: '瑞典语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  GIB: {
    iso3: 'GIB',
    name: '直布罗陀',
    nameEn: 'Gibraltar',
    flag: '🇬🇮',
    primaryLanguage: '英语',
    secondaryLanguages: ['西班牙语'],
    englishProficiency: 'native',
    languages: ['en', 'es'],
  },
  ANT: {
    iso3: 'ANT',
    name: '南极洲',
    nameEn: 'Antarctica',
    flag: '🇦🇶',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'high',
    languages: ['en'],
  },
  ATF: {
    iso3: 'ATF',
    name: '法属南部领地',
    nameEn: 'French Southern Territories',
    flag: '🇹🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  SPM: {
    iso3: 'SPM',
    name: '圣皮埃尔和密克隆',
    nameEn: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  WLF: {
    iso3: 'WLF',
    name: '瓦利斯和富图纳',
    nameEn: 'Wallis and Futuna',
    flag: '🇼🇫',
    primaryLanguage: '法语',
    secondaryLanguages: [],
    englishProficiency: 'low',
    languages: ['fr'],
  },
  ABW: {
    iso3: 'ABW',
    name: '阿鲁巴',
    nameEn: 'Aruba',
    flag: '🇦🇼',
    primaryLanguage: '荷兰语',
    secondaryLanguages: ['帕皮阿门托语', '英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  CUW: {
    iso3: 'CUW',
    name: '库拉索',
    nameEn: 'Curaçao',
    flag: '🇨🇼',
    primaryLanguage: '荷兰语',
    secondaryLanguages: ['帕皮阿门托语', '英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  SXM: {
    iso3: 'SXM',
    name: '荷属圣马丁',
    nameEn: 'Sint Maarten',
    flag: '🇸🇽',
    primaryLanguage: '荷兰语',
    secondaryLanguages: ['英语'],
    englishProficiency: 'high',
    languages: ['en'],
  },
  FLK: {
    iso3: 'FLK',
    name: '福克兰群岛',
    nameEn: 'Falkland Islands',
    flag: '🇫🇰',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  SGS: {
    iso3: 'SGS',
    name: '南乔治亚和南桑威奇群岛',
    nameEn: 'South Georgia',
    flag: '🇬🇸',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  SHN: {
    iso3: 'SHN',
    name: '圣赫勒拿',
    nameEn: 'Saint Helena',
    flag: '🇸🇭',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  PCN: {
    iso3: 'PCN',
    name: '皮特凯恩群岛',
    nameEn: 'Pitcairn Islands',
    flag: '🇵🇳',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  IOT: {
    iso3: 'IOT',
    name: '英属印度洋领地',
    nameEn: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  VGB: {
    iso3: 'VGB',
    name: '英属维尔京群岛',
    nameEn: 'British Virgin Islands',
    flag: '🇻🇬',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  CYM: {
    iso3: 'CYM',
    name: '开曼群岛',
    nameEn: 'Cayman Islands',
    flag: '🇰🇾',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  BMU: {
    iso3: 'BMU',
    name: '百慕大',
    nameEn: 'Bermuda',
    flag: '🇧🇲',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  TCA: {
    iso3: 'TCA',
    name: '特克斯和凯科斯群岛',
    nameEn: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  MSR: {
    iso3: 'MSR',
    name: '蒙特塞拉特',
    nameEn: 'Montserrat',
    flag: '🇲🇸',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  AIA: {
    iso3: 'AIA',
    name: '安圭拉',
    nameEn: 'Anguilla',
    flag: '🇦🇮',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  VIR: {
    iso3: 'VIR',
    name: '美属维尔京群岛',
    nameEn: 'U.S. Virgin Islands',
    flag: '🇻🇮',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  GUM: {
    iso3: 'GUM',
    name: '关岛',
    nameEn: 'Guam',
    flag: '🇬🇺',
    primaryLanguage: '英语',
    secondaryLanguages: ['查莫罗语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  ASM: {
    iso3: 'ASM',
    name: '美属萨摩亚',
    nameEn: 'American Samoa',
    flag: '🇦🇸',
    primaryLanguage: '英语',
    secondaryLanguages: ['萨摩亚语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  MNP: {
    iso3: 'MNP',
    name: '北马里亚纳群岛',
    nameEn: 'Northern Mariana Islands',
    flag: '🇲🇵',
    primaryLanguage: '英语',
    secondaryLanguages: ['查莫罗语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  NFK: {
    iso3: 'NFK',
    name: '诺福克岛',
    nameEn: 'Norfolk Island',
    flag: '🇳🇫',
    primaryLanguage: '英语',
    secondaryLanguages: [],
    englishProficiency: 'native',
    languages: ['en'],
  },
  CCK: {
    iso3: 'CCK',
    name: '科科斯群岛',
    nameEn: 'Cocos Islands',
    flag: '🇨🇨',
    primaryLanguage: '英语',
    secondaryLanguages: ['马来语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  CXR: {
    iso3: 'CXR',
    name: '圣诞岛',
    nameEn: 'Christmas Island',
    flag: '🇨🇽',
    primaryLanguage: '英语',
    secondaryLanguages: ['中文'],
    englishProficiency: 'native',
    languages: ['en', 'zh'],
  },
  COK: {
    iso3: 'COK',
    name: '库克群岛',
    nameEn: 'Cook Islands',
    flag: '🇨🇰',
    primaryLanguage: '英语',
    secondaryLanguages: ['毛利语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  NIU: {
    iso3: 'NIU',
    name: '纽埃',
    nameEn: 'Niue',
    flag: '🇳🇺',
    primaryLanguage: '英语',
    secondaryLanguages: ['纽埃语'],
    englishProficiency: 'native',
    languages: ['en'],
  },
  TKL: {
    iso3: 'TKL',
    name: '托克劳',
    nameEn: 'Tokelau',
    flag: '🇹🇰',
    primaryLanguage: '英语',
    secondaryLanguages: ['托克劳语'],
    englishProficiency: 'medium',
    languages: ['en'],
  },
  MAC: {
    iso3: 'MAC',
    name: '澳门',
    nameEn: 'Macau',
    flag: '🇲🇴',
    primaryLanguage: '中文',
    secondaryLanguages: ['葡萄牙语'],
    englishProficiency: 'medium',
    languages: ['zh', 'pt'],
  },
};

// Helper function to get English proficiency label
export const getEnglishProficiencyLabel = (level: string): { text: string; color: string } => {
  switch (level) {
    case 'native':
      return { text: '母语', color: 'text-green-600' };
    case 'high':
      return { text: '高', color: 'text-blue-600' };
    case 'medium':
      return { text: '中', color: 'text-yellow-600' };
    case 'low':
      return { text: '低', color: 'text-red-600' };
    default:
      return { text: '未知', color: 'text-gray-600' };
  }
};

// Helper function to get complete country info with default values
export const getCountryInfo = (iso3: string): CountryLanguageInfo | null => {
  const country = COUNTRY_LANGUAGES[iso3];
  if (!country) return null;

  // Provide default values for new fields if missing
  return {
    ...country,
    googleMapsLang: country.googleMapsLang || country.primaryLanguage,
    businessLang: country.businessLang || (country.englishProficiency === 'native' || country.englishProficiency === 'high' ? '英语' : country.primaryLanguage),
    businessLangAlt: country.businessLangAlt,
    businessNote: country.businessNote || (country.englishProficiency === 'native' ? '直接用英语' :
      country.englishProficiency === 'high' ? '英语可行' :
        country.englishProficiency === 'medium' ? '英语在商务场合可行' :
          `建议用${country.primaryLanguage}`),
    preferredMessenger: country.preferredMessenger || 'whatsapp',
    whatsappPopularity: country.whatsappPopularity || (country.englishProficiency === 'low' ? 'medium' : 'high'),
  };
};

// Get WhatsApp popularity label
export const getWhatsappPopularityLabel = (level: string): { text: string; color: string } => {
  switch (level) {
    case 'high':
      return { text: '普及', color: 'text-green-600' };
    case 'medium':
      return { text: '一般', color: 'text-yellow-600' };
    case 'low':
      return { text: '较少', color: 'text-red-600' };
    default:
      return { text: '未知', color: 'text-gray-600' };
  }
};
